name: Test Scheduled Workflow
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Test scheduled workflow triggered at $(date)"
